const GameIndexConstants = {
  GAMES_RECEIVED: "GAMES_RECEIVED",
  GAME_RECEIVED: 'GAME_RECEIVED',
  GAME_REMOVED: "GAME_REMOVED",
  USER_COUNT_RECEIVED: "USER_COUNT_RECEIVED",
  ERROR_RECEIVED: "ERROR_RECEIVED"
};

export default GameIndexConstants;
