const GameConstants = {
  GAME_RECEIVED: 'GAME_RECEIVED',
  STATE_RECEIVED: 'STATE_RECEIVED',
  GAMESTATE_RECEIVED: "GAMESTATE_RECEIVED",
  ERROR_RECEIVED: "ERROR_RECEIVED",
  GAME_OVER: "GAME_OVER"
};

export default GameConstants;
