const GameIndexConstants = {
  GAMES_RECEIVED: "GAMES_RECEIVED",
  GAME_RECEIVED: 'GAME_RECEIVED',
  GAMES_REMOVED: 'GAMES_REMOVED',
  GAME_REMOVED: "GAME_REMOVED",
  ERROR_RECEIVED: "ERROR_RECEIVED",
  SORT: "SORT",
  STATUSES: "STATUSES"
};

export default GameIndexConstants;
